-- DEPARTMENTS 테이블에서 DEPARTMENT_NAME이 Marketing 인 데이터 조회
SELECT * FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME LIKE 'Marketing';

-- DEPARTMENTS 테이블에서 DEPARTMENT_NAME이 IT가 포함된 데이터 조회
SELECT * FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME LIKE '%IT%';

-- LOCATIONS 테이블에서 COUNTRY_ID가 US인 데이터 조회할 때, STREET_ADDRESS, POSTAL_CODE, CITY 컬럼만 조회한다
SELECT STREET_ADDRESS
	 , POSTAL_CODE
	 , CITY 
  FROM LOCATIONS
 WHERE COUNTRY_ID LIKE 'US';

-- LOCATIONS 테이블에서 POSTAL_CODE 가 5자리인 데이터 조회
SELECT * FROM LOCATIONS
 WHERE POSTAL_CODE LIKE '_____';

-- EMPLOYEES 테이블에서 MANAGER_ID가 100이고 DEPARTMENT_ID가 50인 데이터 조회
SELECT * FROM EMPLOYEES
 WHERE MANAGER_ID = '100'
 	 AND DEPARTMENT_ID = '50';
 	
-- EMPLOYEES 테이블에서 COMMISSION_PCT가 NULL이 아니면서 SALARY가 10000 이상인
-- 데이터를 조회할 때 COMMISSION_PCT가 포함된 급여로 조회
-- SALARY, COMMISSION_PCT, TOTAL_SALARY 컬럼명으로 결과가 나오게 한다
 	-- TOTAL_SALARY는 SALARY * (1 + COMMISION_PCT) 계산 결과로 나오게 한다.
SELECT SALARY
	 , COMMISSION_PCT
	 , SALARY * (1 + COMMISSION_PCT) || '$' "TOTAL_SALARY"
	 FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
  	AND SALARY >= 10000;
  
-- EMPLOYEES 테이블에서 MANAGER_ID가 100,101,102,200,201,202 인 데이터 조회
-- FIRST_NAME, LAST_NAME은 하나의 컬럼(EMP_NAME)으로 조회되도록 한다.
SELECT FIRST_NAME
	 , LAST_NAME
	 , FIRST_NAME || ' ' || LAST_NAME "EMP_NAME" 
  FROM EMPLOYEES
 WHERE MANAGER_ID BETWEEN 101 AND 102
   OR MANAGER_ID BETWEEN 200 AND 202; 
   
--EMPLOYEES 테이블에서 EMAIL 컬럼을 조회할 때 EMAIL@JOB_ID.employee.com 형식으로 조회 되도록 한다
--예 ) EMPLOYEE_ID 가 100인 사원은 EMAIL이 SKING, JOB_ID가 AD_PRES이다. 
--이를 문제에서 제시하는 형식으로 조회하면 SKING@AD_PRES.employee.com으로 조회다 된다
SELECT EMPLOYEE_ID || '@' || JOB_ID || '.employee.com' "EMAIL" 
 FROM EMPLOYEES;