/*
 * 데이터 잘 들어갔는지 확인 하는 테이블 - HR정보 확인
 */

-- 직원 테이블
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID > 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID != 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID <> 100;

-- 부서 테이블
SELECT * FROM DEPARTMENTS;
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;
-- 직급 테이블
SELECT * FROM JOBS;

-- 나라 테이블
SELECT * FROM COUNTRIES;

-- 지역 테이블(해당 국가)
SELECT * FROM LOCATIONS;

-- 대륙 정보 테이블(아프리카, 아시아 ... )
SELECT * FROM REGIONS;

